
try {
    helloWorldFunction();
} catch ( error ) { // We can accept an argument: the error object, if we'd like.
    console.log( error );
}
